"use strict";
console.log("Hey Abu Hurairah,I have started learning TYPESCRIPT");
var naMe = ("Fatima");
console.log(naMe);
var num1 = 1;
var num2 = 2;
var num3 = 3;
var num4 = 4;
var num5 = 5;
var num6 = 6;
var num7 = 7;
var num8 = 8;
var num9 = 9;
var num10 = 10;
var addition = (num1 + num2 + num3 + num4 + num5 + num6 + num7 + num8 + num9 + num10);
var subtraction = (num1 - num2 - num3 - num4 - num5 - num6 - num7 - num8 - num9 - num10);
var multiply = (num1 * num2 * num3 * num4 * num5 * num6 * num7 * num8 * num9 * num10);
var divison = (num10 / num5);
console.log(addition);
console.log(subtraction);
console.log(multiply);
console.log(divison);
