console.log("Hey Abu Hurairah,I have started learning TYPESCRIPT");
var naMe:string = ("Fatima");
console.log(naMe);
var num1:number = 1 ;
var num2:number = 2 ;
var num3:number = 3 ;
var num4:number = 4 ;
var num5:number = 5 ;
var num6:number = 6 ;
var num7:number = 7 ;
var num8:number = 8 ;
var num9:number = 9 ;
var num10:number =10;
var addition:number = (num1+num2+ num3+num4+num5+num6+num7+num8+num9+num10);
var subtraction:number = (num1-num2- num3-num4-num5-num6-num7-num8-num9-num10);
var multiply:number = (num1*num2*num3*num4*num5*num6*num7*num8*num9*num10);
var divison:number = (num10/num5);
console.log(addition);
console.log(subtraction);
console.log(multiply);
console.log(divison);